// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAblNJ9nWzTAdvhy2zZmoF3g8udL54cOtw',
    appId: '1:352373217860:web:f3eb92e2c2d07433e1fa11',
    messagingSenderId: '352373217860',
    projectId: 'grow-life-8ae8c',
    authDomain: 'grow-life-8ae8c.firebaseapp.com',
    storageBucket: 'grow-life-8ae8c.appspot.com',
    measurementId: 'G-REJ7GR8HFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbd3-1-ZKilnaFDMyTLxSou2D5AT1yxVM',
    appId: '1:352373217860:android:bce2934203ba0c97e1fa11',
    messagingSenderId: '352373217860',
    projectId: 'grow-life-8ae8c',
    storageBucket: 'grow-life-8ae8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JIeXITB4VhhfkSJKzqSEEKcHK4ythLI',
    appId: '1:352373217860:ios:149f927e50c2d70ee1fa11',
    messagingSenderId: '352373217860',
    projectId: 'grow-life-8ae8c',
    storageBucket: 'grow-life-8ae8c.appspot.com',
    iosBundleId: 'com.example.growLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3JIeXITB4VhhfkSJKzqSEEKcHK4ythLI',
    appId: '1:352373217860:ios:149f927e50c2d70ee1fa11',
    messagingSenderId: '352373217860',
    projectId: 'grow-life-8ae8c',
    storageBucket: 'grow-life-8ae8c.appspot.com',
    iosBundleId: 'com.example.growLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAblNJ9nWzTAdvhy2zZmoF3g8udL54cOtw',
    appId: '1:352373217860:web:8fa6f172e68e544ee1fa11',
    messagingSenderId: '352373217860',
    projectId: 'grow-life-8ae8c',
    authDomain: 'grow-life-8ae8c.firebaseapp.com',
    storageBucket: 'grow-life-8ae8c.appspot.com',
    measurementId: 'G-1WETQBTPTL',
  );
}
